"""Track the live counters of a Kimi Code CLI session.

Usage (run from the skills workspace root):
    track_session.py <uuid>
    track_session.py <uuid> --sessions-dir PATH

The script accepts either:
- a probe UUID generated by the agent for the current conversation; the probe
  is looked up inside ~/.kimi/sessions to discover the real session directory;
- the real session UUID, in which case the directory is resolved directly.

Output is a single JSON line written to stdout.
"""

# ruff: noqa: INP001, T201 — CLI script, not a package; print is the interface.

import argparse
import json
import logging
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass
from enum import StrEnum, auto
from pathlib import Path

logger = logging.getLogger(__name__)

ENCODING = "utf-8"
STATUS_UPDATE_TYPE = "StatusUpdate"
MESSAGE_TYPE_KEY = "type"
MESSAGE_KEY = "message"
PAYLOAD_KEY = "payload"
USAGE_BLOCK_FIELD = "token_usage"
MAX_RG_HITS = 1
SESSION_DIR_DEPTH = 2
DEFAULT_SESSIONS_DIR = Path.home() / ".kimi" / "sessions"
WIRE_FILE = "wire.jsonl"


class SessionInspectorError(Exception):
    """Base error for session inspector scripts."""


class SessionNotFoundError(SessionInspectorError):
    """No session directory matches the supplied id or probe."""


class StatusUpdateNotFoundError(SessionInspectorError):
    """The session directory does not contain a StatusUpdate record."""


class DependencyError(SessionInspectorError):
    """A required external dependency is missing or misbehaving."""


class FoundBy(StrEnum):
    """How the session directory was discovered."""

    DIRECT = auto()
    PROBE = auto()
    NOT_FOUND = auto()


@dataclass(frozen=True)
class TokenUsage:
    """Token counters from a StatusUpdate payload."""

    input_other: int
    output: int
    input_cache_read: int
    input_cache_creation: int


@dataclass(frozen=True)
class StatusPayload:
    """The distilled StatusUpdate payload."""

    context_usage: float
    context_tokens: int
    max_context_tokens: int
    token_usage: TokenUsage
    message_id: str
    plan_mode: bool
    mcp_status: object | None


@dataclass(frozen=True)
class TrackResult:
    """JSON-serializable result emitted by the script."""

    session_id: str | None
    found_by: FoundBy
    status: StatusPayload | None
    error: str | None


def _find_session_dir_direct(uuid: str, root: Path) -> Path | None:
    """Return the session directory whose name equals uuid, if it exists."""
    for project_dir in root.iterdir():
        candidate = project_dir / uuid
        if candidate.is_dir():
            return candidate
    return None


def _find_session_dir_by_probe(probe: str, root: Path) -> Path:
    """Use rg to locate a session file containing probe, then return its dir."""
    rg_path = shutil.which("rg")
    if rg_path is None:
        raise DependencyError("rg (ripgrep) is not installed")

    # -F treats the probe as a literal string, not a regex.
    result = subprocess.run(  # noqa: S603
        [
            rg_path,
            "-F",
            "--max-count",
            str(MAX_RG_HITS),
            "-l",
            probe,
            str(root),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0 or not result.stdout:
        message = f"probe {probe!r} not found in sessions under {root}"
        raise SessionNotFoundError(message)

    hit_path = Path(result.stdout.splitlines()[0])
    try:
        relative = hit_path.relative_to(root)
    except ValueError as error:
        message = f"rg hit outside sessions root: {hit_path}"
        raise SessionNotFoundError(message) from error

    if len(relative.parts) < SESSION_DIR_DEPTH:
        message = f"rg hit does not contain a session directory: {hit_path}"
        raise SessionNotFoundError(message)

    session_dir = root / relative.parts[0] / relative.parts[1]
    if not session_dir.is_dir():
        message = f"resolved session directory does not exist: {session_dir}"
        raise SessionNotFoundError(message)

    return session_dir


def resolve_session_dir(uuid: str, root: Path) -> Path:
    """Resolve a session directory by direct id or by probe lookup."""
    direct = _find_session_dir_direct(uuid, root)
    if direct is not None:
        return direct
    return _find_session_dir_by_probe(uuid, root)


def _build_token_usage(raw: dict) -> TokenUsage:
    """Build a TokenUsage value from a raw payload dict."""
    token_usage = raw[USAGE_BLOCK_FIELD]
    return TokenUsage(
        input_other=token_usage["input_other"],
        output=token_usage["output"],
        input_cache_read=token_usage["input_cache_read"],
        input_cache_creation=token_usage["input_cache_creation"],
    )


def _build_status_payload(raw: dict) -> StatusPayload:
    """Build a StatusPayload value from a raw payload dict."""
    return StatusPayload(
        context_usage=raw["context_usage"],
        context_tokens=raw["context_tokens"],
        max_context_tokens=raw["max_context_tokens"],
        token_usage=_build_token_usage(raw),
        message_id=raw["message_id"],
        plan_mode=raw["plan_mode"],
        mcp_status=raw.get("mcp_status"),
    )


STATUS_UPDATE_JQ_QUERY = (
    '[.[] | select(.message.type == "StatusUpdate")] | last | .message.payload'
)


def read_latest_status(wire_path: Path) -> StatusPayload:
    """Read the most recent StatusUpdate payload from a wire.jsonl file."""
    jq_path = shutil.which("jq")
    if jq_path is None:
        raise DependencyError("jq is not installed")

    result = subprocess.run(  # noqa: S603
        [jq_path, "-s", STATUS_UPDATE_JQ_QUERY, str(wire_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        message = f"jq failed for {wire_path}: {result.stderr.strip()}"
        raise StatusUpdateNotFoundError(message)

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        message = f"jq output is not valid JSON: {error}"
        raise StatusUpdateNotFoundError(message) from error

    if not isinstance(payload, dict):
        raise StatusUpdateNotFoundError("no StatusUpdate record found")

    try:
        return _build_status_payload(payload)
    except (KeyError, TypeError) as error:
        message = f"StatusUpdate payload malformed: {error}"
        raise StatusUpdateNotFoundError(message) from error


def _emit(result: TrackResult) -> None:
    """Print the result as a single JSON line."""
    print(json.dumps(asdict(result), ensure_ascii=False))


def main() -> None:
    """Parse arguments, resolve the session, and emit counters."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("uuid", help="session UUID or probe UUID")
    parser.add_argument(
        "--sessions-dir",
        type=Path,
        default=DEFAULT_SESSIONS_DIR,
        help="override the sessions root (default: ~/.kimi/sessions)",
    )
    args = parser.parse_args()

    root = args.sessions_dir
    if not root.is_dir():
        _emit(
            TrackResult(
                session_id=None,
                found_by=FoundBy.NOT_FOUND,
                status=None,
                error=f"sessions dir not found: {root}",
            ),
        )
        return

    try:
        session_dir = resolve_session_dir(args.uuid, root)
    except SessionNotFoundError:
        _emit(
            TrackResult(
                session_id=None,
                found_by=FoundBy.NOT_FOUND,
                status=None,
                error=None,
            ),
        )
        return
    except DependencyError as error:
        _emit(
            TrackResult(
                session_id=None,
                found_by=FoundBy.NOT_FOUND,
                status=None,
                error=str(error),
            ),
        )
        return

    found_by = FoundBy.DIRECT if session_dir.name == args.uuid else FoundBy.PROBE

    try:
        status = read_latest_status(session_dir / WIRE_FILE)
    except StatusUpdateNotFoundError as error:
        logger.debug("status not available: %s", error)
        status = None

    _emit(
        TrackResult(
            session_id=session_dir.name,
            found_by=found_by,
            status=status,
            error=None,
        ),
    )


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.WARNING,
        stream=sys.stderr,
        format="%(levelname)s: %(message)s",
    )
    main()
